#!/usr/bin/python
#
# Copyright (C) 2007 Red Hat, Inc.
# Authors:
# Thomas Woerner <twoerner@redhat.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import signal
import sys

try:
    import gtk
except:
    import os
    argv = [ "/usr/bin/system-config-firewall-tui" ]
    os.execv(argv[0], argv)

DATADIR = '/root/scf/'
import sys
sys.path.append(DATADIR)

import fw_config
import fw_gui

if __name__ == "__main__":
    signal.signal (signal.SIGINT, signal.SIG_DFL)

if "--no-dbus" in sys.argv:
    use_dbus = False
else:
    use_dbus = True

fw_config.ui = fw_gui.ui(use_dbus)
fw_config.ui.run()
